In [3]:
import numpy as np

In [4]:
first_numpy_array = np.array([1,5,3,6])
print(first_numpy_array)

[1 5 3 6]


In [5]:
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np_arange = np.arange(12)
np_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
np_linspace =np.linspace(1,8,5)
np_linspace

array([1.  , 2.75, 4.5 , 6.25, 8.  ])

In [10]:
ThreeD_array = np.arange(27).reshape(3,3,3)
ThreeD_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [52]:
np.array(24)

array(24)

In [12]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [13]:
np.array([[1,1,1],
         [1,2,1]])

array([[1, 1, 1],
       [1, 2, 1]])

In [14]:
np.array([[[1,1,1],
         [2,2,2]],[[3,3,3],[4,4,4]]])

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]]])

In [15]:
numpy_arr = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])

In [16]:
numpy_arr.shape

(2, 2, 3)

In [17]:
numpy_arr.ndim

3

In [18]:
A = ([1,3,8],[2,3,5])
B = ([1,8,4])

In [19]:
#dodawanie
np.add(A,B)

array([[ 2, 11, 12],
       [ 3, 11,  9]])

In [20]:
#odejmowanie
np.subtract(B,A)

array([[ 0,  5, -4],
       [-1,  5, -1]])

In [21]:
#mnożenie
np.multiply(A,B)

array([[ 1, 24, 32],
       [ 2, 24, 20]])

In [22]:
#dzielenie
np.divide(A,B)

array([[1.   , 0.375, 2.   ],
       [2.   , 0.375, 1.25 ]])

In [23]:
#potęga
np.power(A,2)

array([[ 1,  9, 64],
       [ 4,  9, 25]], dtype=int32)

In [24]:
X = np.array([i for i in range(10)])
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.where(X%2==0, 'Parzysta', 'Nieparzysta')

array(['Parzysta', 'Nieparzysta', 'Parzysta', 'Nieparzysta', 'Parzysta',
       'Nieparzysta', 'Parzysta', 'Nieparzysta', 'Parzysta',
       'Nieparzysta'], dtype='<U11')

In [27]:
condlist = [X<5,X>5]
choicelist = [X**2,X**3]
Y = np.select(condlist,choicelist,default=X)
Y

array([  0,   1,   4,   9,  16,   5, 216, 343, 512, 729])

In [28]:
Z = Y.reshape(2,5)
Z

array([[  0,   1,   4,   9,  16],
       [  5, 216, 343, 512, 729]])

In [29]:
#minimalna liczba
np.amin(Z)

0

In [30]:
#minimalna liczba w osi X
np.amin(Z,axis=0)

array([ 0,  1,  4,  9, 16])

In [31]:
#minimalna liczba w osi Y
np.amin(Z,axis=1)

array([0, 5])

In [32]:
#max liczba w osi X
np.amax(Z,axis=0)

array([  5, 216, 343, 512, 729])

In [33]:
#max liczba w osi Y
np.amax(Z,axis=1)

array([ 16, 729])

In [34]:
np.percentile(Z,50)

12.5

In [35]:
deg = np.array([0,30,45,60,90])
deg

array([ 0, 30, 45, 60, 90])

In [36]:
np.sin(deg*np.pi/180)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [37]:
#dostęp do poszczególnych liczb z macierzy

In [38]:
array_1d = np.array([1,2,3,4,5,6])
array_1d

array([1, 2, 3, 4, 5, 6])

In [42]:
#pierwszy element maciery 2d
array_1d[0]

1

In [45]:
#cięcie macierzy
array_1d[1:]

array([2, 3, 4, 5, 6])

In [46]:
#cięcie macierzy określony zakres
array_1d[1:5]

array([2, 3, 4, 5])

In [47]:
#inny sposób (od końca)
array_1d[-5:-1]

array([2, 3, 4, 5])

In [39]:
array_2d = np.array([[3,2,1],[4,5,6]])
array_2d

array([[3, 2, 1],
       [4, 5, 6]])

In [49]:
#pierwszy element maciery 2d
array_2d[0,0]

3

In [51]:
#cięcie drugi wiersz od drugiego eleemntu do trzeciego
array_2d[1,0:2]

array([4, 5])

In [53]:
array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [54]:
#ostati element ostatniej macierzy
array_3d[1,1,2]

12

In [55]:
#ostati element ostatniej macierzy
array_3d[-1,-1,-1] 

12

In [56]:
#druga macierz, wiersze od drugiego do końca, kolumny od drugiej do końca
array_3d[1,1:,1:]

array([[11, 12]])